SaeArtchipel/SaeArtchipel/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from api import urls as api_urls  # Importez le fichier urls.py de votre application API

urlpatterns = [
    path('admin/', admin.site.urls),

    path('app_admin/',include('app_admin.urls')),


    # Utilisez include avec le module urls de votre application API
    path('api/', include(api_urls)),
]

SaeArtchipel/api/urls.py
from django.urls import path
from api import views
from .token.views import MyTokenObtainPairView
from rest_framework_simplejwt.views import TokenRefreshView
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

# Configuration drf-yasg pour la documentation Swagger
schema_view = get_schema_view(
    openapi.Info(
        title="SaeArtchipel API",
        default_version='v1',
        description="API de l'application SaeArtchipel",
    ),
    public=True,  # Set to False if you want to hide the Swagger UI from unauthorized users
)

urlpatterns = [
    
    #Lieu
    path('lieu/',views.LieuView.as_view(),name="list_lieux"),
    path('lieu/<int:lieu_id>/',views.details_Lieu, name='detail_Lieu'),
    #recupere tous les lieux d'un departement
    path('all_lieux_departement/<int:departement_id>', views.get_all_lieux_departement, name='get_all_lieux_departement'),
   
    #Parcours
    path('parcours/',views.ParcoursView.as_view(),name="list_Parcours"),
    path('parcours/<int:parcours_id>/',views.details_Parcours, name='detail_Parcours'),

    #Evenement
    path('evenement/',views.EvenementView.as_view(), name="list_evenements"),
    path('evenement/<int:evenement_id>/',views.detail_evenement_with_lieu, name='detail_evenement'),

    #Region
    path('region/',views.RegionView.as_view(),name="list_regions"),
    #recupere tous les lieux d'une region
    path('all_lieux_region/<int:region_id>', views.get_all_lieux_region, name='get_all_lieux_region'),

    #Departement
    path('departement/',views.DepartementView.as_view(), name="list_departements"),
    
    #Ville
    path('ville/',views.VilleView.as_view(), name="list_villes"),   
    
    #Horaire
    # path('horaire/',views.HoraireView.as_view(), ),
    
    #Tarif
    path('tarif/',views.TarifView.as_view(), name="list_tarifs"),
    
    #TypeLieu
    path('typelieu/',views.TypeLieuView.as_view(), name="list_typelieu"),

    #LnkLieuHoraire
    # path('lnklieuhoraire/',views.LnkLieuHoraireView.as_view(),),

    #FavorisParcours
    path('favorisparcours/',views.FavorisParcoursView.as_view(), name="list_favorisparcours"),

    #PreferenceLieu
    path('preferencelieu/',views.PreferenceLieuView.as_view(), name="list_preferencelieu"),

    #Oeuvre
    path('oeuvre/',views.OeuvreProximiteView.as_view(), name="list_oeuvres_proximite"),

    #recupere toutes les oeuvres à proximité dans un departement
    path('oeuvre/<int:departement_id>', views.get_all_oeuvres_proximites_departement, name='get_all_oeuvres_proximites_departement'),
    
    path('tojson/',views.tojson, name='tojson'),

    #partie token
    path('token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh', TokenRefreshView.as_view(), name='token_refresh_pair'),

    #creation utilisateur
    path('register/', views.RegisterView.as_view(), name='auth_register'),

    # Configuration drf-yasg pour la documentation Swagger
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    #modification informations utilisateur
    path('update-user/<int:user_id>',views.update_user, name='update-user'),

    #recuperer les parcours favoris d'un utilisateur
    path('favoris-parcours/<int:user_id>',views.get_favoris_parcours, name='get-favoris-parcours'),

    path('favoris-lieu/<int:user_id>',views.get_favoris_lieu, name='get-favoris-lieu'),


    #reste à faire 
    #recuperer les parcours d'un utilisateur

    #creation d'un parcours avec des etapes 

    #modification d'un parcours avec des etapes 

    #suppression d'un parcours avec ces etapes

]

SaeArtchipel/app_admin/urls.py
from django.urls import path
from .views import ParcoursProposeView, home, liste_regions, liste_departements, liste_villes, liste_typelieux, liste_lieux
from .views import RegionCreateView, RegionUpdateView, RegionDeleteView, DepartementCreateView, DepartementUpdateView, DepartementDeleteView, VilleCreateView, VilleUpdateView, VilleDeleteView, TypeLieuCreateView, TypeLieuUpdateView, TypeLieuDeleteView, LieuCreateView, LieuUpdateView, LieuDeleteView, HoraireView, LnkLieuHoraireView, ParcoursListView, ParcoursDetailView, DeleteViewParcours, ParcoursCreateView,edit_parcours, ListeEtape, add_etape_parcours, login_view, user_logout


app_name = 'app_admin'

urlpatterns = [
    path('',home, name='home' ),

    path('regions/', liste_regions, name='liste_regions'),
    path('region/ajouter/', RegionCreateView.as_view(), name='ajouter_region'),
    path('region/modifier/<int:pk>/', RegionUpdateView.as_view(), name='modifier_region'),
    path('region/supprimer/<int:pk>/', RegionDeleteView.as_view(), name='supprimer_region'),

    path('departements/', liste_departements, name='liste_departements'),
    path('departement/ajouter/', DepartementCreateView.as_view(), name='ajouter_departement'),
    path('departement/modifier/<int:pk>/', DepartementUpdateView.as_view(), name='modifier_departement'),
    path('departement/supprimer/<int:pk>/', DepartementDeleteView.as_view(), name='supprimer_departement'),

    path('villes/', liste_villes, name='liste_villes'),
    path('ville/ajouter/', VilleCreateView.as_view(), name='ajouter_ville'),
    path('ville/modifier/<int:pk>/', VilleUpdateView.as_view(), name='modifier_ville'),
    path('ville/supprimer/<int:pk>/', VilleDeleteView.as_view(), name='supprimer_ville'),

    path('typelieux/', liste_typelieux, name='liste_typelieux'),
    path('typelieu/ajouter/', TypeLieuCreateView.as_view(), name='ajouter_typelieu'),
    path('typelieu/modifier/<int:pk>/', TypeLieuUpdateView.as_view(), name='modifier_typelieu'),
    path('typelieu/supprimer/<int:pk>/', TypeLieuDeleteView.as_view(), name='supprimer_typelieu'),

    path('lieux/', liste_lieux, name='liste_lieux'),
    path('lieu/ajouter/', LieuCreateView.as_view(), name='ajouter_lieu'),
    path('lieu/modifier/<int:pk>/', LieuUpdateView.as_view(), name='modifier_lieu'),
    path('lieu/supprimer/<int:pk>/', LieuDeleteView.as_view(), name='supprimer_lieu'),

    path('horaire/<int:lieu_id>/', HoraireView.as_view(), name='horaire-view'),
    path('lnk-lieu-horaire/<int:lieu_id>/<int:horaire_id>/', LnkLieuHoraireView.as_view(), name='lnk-lieu-horaire-view'),

    path('parcours-liste/', ParcoursListView.as_view(), name='liste_parcours'),
    path('parcours-detail/<int:pk>/', ParcoursDetailView.as_view(), name='get_parcours'),
    path('supprimer-parcours/<int:pk>/', DeleteViewParcours.as_view(), name='delete_parcours'),
    path('creer-parcours/', ParcoursCreateView.as_view(), name='add_parcours'),
    path('proposer-parcours/', ParcoursProposeView.as_view(), name='pro_parcours'),
    path('parcours/edit/<int:parcours_id>/', edit_parcours, name='edit_parcours'),
    path('parcours_liste_etapes/<int:parcours_id>', ParcoursDetailView.as_view(), name='get_liste_etape' ),
    path('liste_all_lieux/<int:parcours_id>', ListeEtape.as_view(), name='liste_lieux_etapes'),
    path('ajouter_etape/', add_etape_parcours, name="ajouter_etape"),

    path('login/', login_view, name='login'),
    path('logout/', user_logout, name='logout'),


    # path('/regions/', liste_regions, name='liste_regions'),
    # path('/region/ajouter/', RegionCreateView.as_view(), name='ajouter_region'),
    # path('/region/modifier/<int:pk>/', RegionUpdateView.as_view(), name='modifier_region'),
    # path('/region/supprimer/<int:pk>/', RegionDeleteView.as_view(), name='supprimer_region'),

    # path('/regions/', liste_regions, name='liste_regions'),
    # path('/region/ajouter/', RegionCreateView.as_view(), name='ajouter_region'),
    # path('/region/modifier/<int:pk>/', RegionUpdateView.as_view(), name='modifier_region'),
    # path('/region/supprimer/<int:pk>/', RegionDeleteView.as_view(), name='supprimer_region'),

    # path('/regions/', liste_regions, name='liste_regions'),
    # path('/region/ajouter/', RegionCreateView.as_view(), name='ajouter_region'),
    # path('/region/modifier/<int:pk>/', RegionUpdateView.as_view(), name='modifier_region'),
    # path('/region/supprimer/<int:pk>/', RegionDeleteView.as_view(), name='supprimer_region'),

    # path('/regions/', liste_regions, name='liste_regions'),
    # path('/region/ajouter/', RegionCreateView.as_view(), name='ajouter_region'),
    # path('/region/modifier/<int:pk>/', RegionUpdateView.as_view(), name='modifier_region'),
    # path('/region/supprimer/<int:pk>/', RegionDeleteView.as_view(), name='supprimer_region'),
]

SaeArtchipel/api/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import AbstractUser


class Utilisateur(AbstractUser):

    ddnUtilisateur = models.DateField(format('%d/%m/%Y'),null=True)
    
    def __str__(self):
            return f"[\n User : {self.username} \n Email : {self.email} \n Type : {self.is_superuser} \n]"
    
class PreferenceLieu(models.Model):
    idUtilisateur = models.ForeignKey(Utilisateur, on_delete=models.CASCADE)
    idLieu = models.ForeignKey('Lieu', on_delete=models.CASCADE)
    
    def __str__(self):
            return f"[\n User : {self.idUtilisateur} \n Lieu : {self.idLieu} \n]"

class FavorisParcours(models.Model):
    idUtilisateur = models.ForeignKey(Utilisateur, on_delete=models.CASCADE)
    idParcours = models.ForeignKey('Parcours', on_delete=models.CASCADE)
    
    def __str__(self):
            return f"[\n User : {self.idUtilisateur} \n Parcours : {self.idParcours} \n]"
    
class Parcours(models.Model):
    idParcours = models.AutoField(primary_key=True)
    nomParcours = models.CharField(max_length=200)
    idUtilisateur = models.ForeignKey(Utilisateur, on_delete=models.CASCADE)
    typeParcours = models.CharField(max_length=200)
    difficulteParcours = models.CharField(max_length=100)
    distanceParcours = models.IntegerField()
    
    def __str__(self):
            return f"[\n Parcours : {self.nomParcours} \n Type : {self.typeParcours} \n Difficulté : {self.difficulteParcours} \n Distance : {self.distanceParcours} \n]"
    
class Etape(models.Model):
    idParcours = models.ForeignKey(Parcours, on_delete=models.CASCADE)
    idLieu = models.ForeignKey('Lieu', on_delete=models.CASCADE)
    numEtape = models.IntegerField()
    
    def __str__(self):
            return f"[\n Parcours : {self.idParcours} \n Lieu : {self.idLieu} \n Numéro : {self.numEtape} \n]"

class Lieu(models.Model):
        idLieu = models.AutoField(primary_key=True)
        nomLieu = models.CharField(max_length=150, unique=True)
        descriptionLieu = models.CharField(max_length=7000, null=True)
        imageLieu = models.ImageField(null=True)
        boolPompidouLieu = models.BooleanField(default=False)
        boolAccessibilite = models.BooleanField()
        boolParking = models.BooleanField()
        boolShopping = models.BooleanField()
        boolRepas = models.BooleanField()
        boolJaujeLieux = models.BooleanField()
        nombreMaxVisiteur = models.IntegerField()
        adresseLieu = models.CharField(max_length=250,null=True)
        latitudeLieu = models.FloatField(null=True)
        longitudeLieu = models.FloatField(null=True)
        telLieu = models.IntegerField(validators=[MinValueValidator(0000000000), MaxValueValidator(9999999999)], null=True)
        mailLieu = models.CharField(max_length=150, null=True)
        webLieu = models.CharField(max_length=250, null=True)
        observationLieu = models.CharField(max_length=7000, null=True)
        idVille = models.ForeignKey('Ville', on_delete=models.CASCADE)
        idTarif = models.ForeignKey('Tarif', on_delete=models.CASCADE)
        idTypeLieu = models.ForeignKey('TypeLieu', on_delete=models.CASCADE)

        def __str__(self):
            return f"[\n idLieu : {self.idLieu} \n Lieu : {self.nomLieu} \n Adresse : {self.adresseLieu} \n]"

class Horaire(models.Model):
    idHoraire = models.AutoField(primary_key=True)
    observationHoraire = models.CharField(max_length=300, null=True)
    horaireOuverture = models.TimeField(null=True)
    horaireFermeture = models.TimeField(null=True)
    intervalHoraire = models.BooleanField()
    lienReservationHoraire = models.CharField(max_length=250, null=True)


    def __str__(self):
        return f"[\n Horaire : {self.observationHoraire} \n Ouverture : {self.horaireOuverture} \n Fermeture : {self.horaireFermeture} \n ]"

class TypeLieu(models.Model):
    idTypeLieu = models.AutoField(primary_key=True)
    nomTypeLieu = models.CharField(max_length=150, unique=True)
    
    def __str__(self):
            return f"[\n Type Lieu : {self.nomTypeLieu} \n]"

class Tarif(models.Model):
    idTarif = models.AutoField(primary_key=True)
    payant = models.BooleanField()
    reservation = models.BooleanField()
    
    def __str__(self):
            return f"[\n Tarif payant : {self.payant} \n reservation : {self.reservation} \n]"

class Ville(models.Model):
    idVille = models.AutoField(primary_key=True)
    nomVille = models.CharField(max_length=200, unique=True)
    codePostal = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(99999)])
    idDepartement = models.ForeignKey('Departement', on_delete=models.CASCADE)
    
    def __str__(self):
            return f"[\n Ville : {self.nomVille} \n Code Postal : {self.codePostal} \n]"

class Departement(models.Model):
    idDepartement = models.AutoField(primary_key=True)
    nomDepartement = models.CharField(max_length=200, unique=True)
    numeroDepartement = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(99)])
    idRegion = models.ForeignKey('Region', on_delete=models.CASCADE)
    
    def __str__(self):
            return f"[\n Département : {self.nomDepartement} \n Numéro : {self.numeroDepartement} \n]"

class Region(models.Model):
    idRegion = models.AutoField(primary_key=True)
    nomRegion = models.CharField(max_length=200, unique=True)
    
    def __str__(self):
            return f"[\n Région : {self.nomRegion} \n]"
    
class Evenement(models.Model):
    idEvenement = models.AutoField(primary_key=True)
    nomEvenement = models.CharField(max_length=200, unique=True)
    descriptionEvenement = models.CharField(max_length=7000, null=True)
    prixEvenement = models.FloatField(null=True)
    dateEvenement = models.DateField(null=True)
    heureEvenement = models.TimeField(null=True)
    infoEvenement = models.CharField(max_length=7000, null=True)
    adresseEvenement = models.CharField(max_length=500, null=True)
    lienreservationEvenement = models.CharField(max_length=500, null=True)
    idLieu = models.ForeignKey(Lieu, on_delete=models.CASCADE)
    
    def __str__(self):
            return f"[\n Evenement : {self.nomEvenement} \n Description : {self.descriptionEvenement} \n Lieu : {self.idLieu} \n]"

class LnkLieuHoraire(models.Model):
    idLieu = models.ForeignKey(Lieu, on_delete=models.CASCADE)
    idHoraire = models.ForeignKey(Horaire, on_delete=models.CASCADE)
    dateDebut = models.DateField(null=True)
    dateFin = models.DateField(null=True)
    
    def __str__(self):
            return f"[\n Lieu : {self.idLieu} \n Horaire : {self.idHoraire} \n date de début : {self.dateDebut} \n date de fin: {self.dateFin} \n]"

class FavorisLieu(models.Model):
    idUtilisateur = models.ForeignKey(Utilisateur, on_delete=models.CASCADE)
    idLieu = models.ForeignKey(Lieu, on_delete=models.CASCADE)
    
    def __str__(self):
            return f"[\n User : {self.idUtilisateur} \n Lieu : {self.idLieu} \n]"
"""
liste des tables :
    Utilisateur
    PreferenceLieu
    FavorisParcours
    Parcours
    Etape
    Lieu
    Horaire
    TypeLieu
    Tarif
    Ville
    Departement
    Region
    Evenement
    LnkLieuHoraire
"""

SaeArtchipel/app_admin/models.py
from django.db import models

# Create your models here.

import api.models

SaeArtchipel/app_admin/templates/app_admin/departement_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
  <div class="row justify-content-center m-2">
    <div class="col-6">
      <h1>{% if form.instance.pk %}Modifier{% else %}Ajouter{% endif %} un departement</h1>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Enregistrer</button>
      </form>
    </div>
    
  </div>

</div>

{% endblock %}

SaeArtchipel/app_admin/templates/app_admin/horaire_form.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}">
{% endblock %}

{% block content %}
<div class="container">
  <div class="row justify-content-center m-2">
    <div class="col-6">
      <h1>{% if form.instance.pk %}Modifier{% else %}Ajouter{% endif %} un horaire</h1>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Enregistrer</button>
      </form>
    </div>
    
  </div>

</div>
{% endblock %}

SaeArtchipel/app_admin/templates/app_admin/liste_etapes.html
<div>
    <h2 class="text-center">Liste des lieux:</h2>
    <p class="text-center">Ajouter un lieu pour une étape du parcours</p>
    <ul>
        {% for lieu in lieux %}

            <li class="list-group-item d-flex justify-content-between align-items-center m-1" style="border:2px solid; border-radius: 20px;">
                <div class="container">
                    <div class="row">  
                        <div class="col-9 d-flex"> 
                        <p >
                            # Lieu : {{ lieu.nomLieu }}, ville: {{ lieu.idVille.nomVille }} ({{ lieu.idVille.codePostal }} )
                        </p>
                        <!-- <p>ici:{{parcours.idParcours}}</p> -->
                    </div> 
                        <div class="col-2 d-flex align-items-center">
                            <a hx-post="{% url 'app_admin:ajouter_etape' %}"  hx-vals='{"idParcours": {{ parcours.idParcours }}, "idLieu": {{ lieu.idLieu }} }'
                            hx-target="#liste_etape_parcours" class="btn btn-secondary">Ajouter</a> 
                        </div>
            
                    </div>
                </div>
            
            </li>
        {% endfor %}
    </ul>
</div>

SaeArtchipel/app_admin/templates/app_admin/parcours.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row justify-content-center m-2">
    <div class="col-12">
        <div class="row">
            <div class="col-2">
                <a href="{% url 'app_admin:pro_parcours' %}" class="btn btn-primary">Proposer un parcours</a>
            </div>
            <div class="col-8">
                <h1 class="text-center">Liste des parcours</h1>
            </div>
            <div class="col-2">
                <a href="{% url 'app_admin:add_parcours' %}" class="btn btn-primary">Créer un parcours</a>
            </div>
        </div>

        <div id="parcours-container" class="row" hx-get="{% url 'app_admin:liste_parcours' %}">
            {% for parcours in parcours_list %}
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ parcours.nomParcours }}</h5>
                        <p class="card-text">Type : {{ parcours.typeParcours }}</p>
                        <p class="card-text">Difficulté : {{ parcours.difficulteParcours }}</p>
                        <p class="card-text">Distance : {{ parcours.distanceParcours }}</p>
                        <p class="card-text">Nombre d'étapes : {{ parcours.nb_etapes }}</p>
                        <div class="row justify-content-center">
                            <div class="container">
                                <div class="row d-flex justify-content-between">
                                    <div class="col-6">
                                        <a class="btn btn-primary" href="{% url 'app_admin:get_parcours' parcours.pk %}">Détails</a>
                                    </div>
                                    <div class="col-6">
                                        <a class="btn btn-danger" href="{% url 'app_admin:delete_parcours' parcours.pk %}">Supprimer</a>
                                    </div>
                                </div>
                                
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

  </div>

</div>
  
{% endblock %}

SaeArtchipel/app_admin/templates/app_admin/parcours_detail.html
<h1>Détail du parcours</h1>
<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ parcours.nomParcours }}</h5>
        <p class="card-text">Type : {{ parcours.typeParcours }}</p>
        <p class="card-text">Difficulté : {{ parcours.difficulteParcours }}</p>
        <p class="card-text">Distance : {{ parcours.distanceParcours }}</p>

        <div>
            <a hx-get="{% url 'app_admin:edit_parcours' parcours.pk %}" hx-target="#detail_parcours" class="btn btn-primary">Modifier</a>
        </div>
    </div>
</div>

SaeArtchipel/app_admin/templates/app_admin/parcours_liste_etapes.html
<h2>Étapes du parcours</h2>
{% if parcours.etape_set.all %}
    <ul>
        {% for etape in parcours.etape_set.all %}
            <li>{{ etape.numEtape }}. Lieu : {{ etape.idLieu.nomLieu }}, ville: {{ etape.idLieu.idVille.nomVille }} ({{ etape.idLieu.idVille.codePostal }} )</li>
            <!-- Ajoutez d'autres informations spécifiques à l'étape si nécessaire -->
        {% endfor %}
    </ul>
{% else %}
    <p>Aucune étape trouvée pour ce parcours.</p>
{% endif %}

SaeArtchipel/app_admin/templates/app_admin/region.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row justify-content-center m-2">
    <div class="col-6">
        <h1>Liste des régions</h1>
        <ul>
          {% for region in regions %}
            <li>{{ region.nomRegion }} - <a href="{% url 'app_admin:modifier_region' region.pk %}">Modifier</a> | <a href="{% url 'app_admin:supprimer_region' region.pk %}">Supprimer</a></li>
          {% endfor %}
        </ul>
        <a href="{% url 'app_admin:ajouter_region' %}">Ajouter une région</a>
    </div>
    
    {% if lieux_with_dates.has_other_pages %}
    <div class="pagination text-center">
      <span class="step-links">
          {% if lieux_with_dates.has_previous %}
            <a href="?page=1" class="btn btn-primary">First</a>
            <a href="?page={{ lieux_with_dates.previous_page_number }}" class="btn btn-primary">&#9664; Previous</a> <!-- Unicode left arrow -->
          {% endif %}
  
          <span class="btn btn-info">
            Page {{ lieux_with_dates.number }} sur {{ lieux_with_dates.paginator.num_pages }}.
          </span>
  
          {% if lieux_with_dates.has_next %}
            <a href="?page={{ lieux_with_dates.next_page_number }}" class="btn btn-primary">Next &#9654;</a> <!-- Unicode right arrow -->
            <a href="?page={{ lieux_with_dates.paginator.num_pages }}" class="btn btn-primary">Last</a>
          {% endif %}
      </span>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

SaeArtchipel/app_admin/templates/app_admin/typelieu.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row justify-content-center m-2">
    <div class="col-6">
      <h1>Liste des types de lieux</h1>
      <ul>
        {% for type in typelieux %}
          <li>{{ type.nomTypeLieu }} - <a href="{% url 'app_admin:modifier_typelieu' type.pk %}">Modifier</a> | <a href="{% url 'app_admin:supprimer_typelieu' type.pk %}">Supprimer</a></li>
        {% endfor %}
      </ul>
      <a href="{% url 'app_admin:ajouter_typelieu' %}">Ajouter un type de lieu</a>
    </div>
    
    {% if lieux_with_dates.has_other_pages %}
    <div class="pagination text-center">
      <span class="step-links">
          {% if lieux_with_dates.has_previous %}
            <a href="?page=1" class="btn btn-primary">First</a>
            <a href="?page={{ lieux_with_dates.previous_page_number }}" class="btn btn-primary">&#9664; Previous</a> <!-- Unicode left arrow -->
          {% endif %}
  
          <span class="btn btn-info">
            Page {{ lieux_with_dates.number }} sur {{ lieux_with_dates.paginator.num_pages }}.
          </span>
  
          {% if lieux_with_dates.has_next %}
            <a href="?page={{ lieux_with_dates.next_page_number }}" class="btn btn-primary">Next &#9654;</a> <!-- Unicode right arrow -->
            <a href="?page={{ lieux_with_dates.paginator.num_pages }}" class="btn btn-primary">Last</a>
          {% endif %}
      </span>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

SaeArtchipel/app_admin/templates/app_admin/ville.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row justify-content-center m-2">
    <div class="col-6">
      <h1>Liste des villes</h1>
      <ul>
        {% for ville in villes %}
          <li>{{ ville.nomVille }} - <a href="{% url 'app_admin:modifier_ville' ville.pk %}">Modifier</a> | <a href="{% url 'app_admin:supprimer_ville' ville.pk %}">Supprimer</a></li>
        {% endfor %}
      </ul>
      <a href="{% url 'app_admin:ajouter_ville' %}">Ajouter une ville</a>

      {% if lieux_with_dates.has_other_pages %}
      <div class="pagination text-center">
        <span class="step-links">
            {% if lieux_with_dates.has_previous %}
              <a href="?page=1" class="btn btn-primary">First</a>
              <a href="?page={{ lieux_with_dates.previous_page_number }}" class="btn btn-primary">&#9664; Previous</a> <!-- Unicode left arrow -->
            {% endif %}
    
            <span class="btn btn-info">
              Page {{ lieux_with_dates.number }} sur {{ lieux_with_dates.paginator.num_pages }}.
            </span>
    
            {% if lieux_with_dates.has_next %}
              <a href="?page={{ lieux_with_dates.next_page_number }}" class="btn btn-primary">Next &#9654;</a> <!-- Unicode right arrow -->
              <a href="?page={{ lieux_with_dates.paginator.num_pages }}" class="btn btn-primary">Last</a>
            {% endif %}
        </span>
      </div>
      {% endif %}
    </div>
  </div>
</div>
  
{% endblock %}