SaeArtchipel/SaeArtchipel/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from api import urls as api_urls  # Importez le fichier urls.py de votre application API

urlpatterns = [
    path('admin/', admin.site.urls),

    path('app_admin/',include('app_admin.urls')),


    # Utilisez include avec le module urls de votre application API
    path('api/', include(api_urls)),
]

SaeArtchipel/api/urls.py
from django.urls import path
from api import views
from .token.views import MyTokenObtainPairView
from rest_framework_simplejwt.views import TokenRefreshView
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

# Configuration drf-yasg pour la documentation Swagger
schema_view = get_schema_view(
    openapi.Info(
        title="SaeArtchipel API",
        default_version='v1',
        description="API de l'application SaeArtchipel",
    ),
    public=True,  # Set to False if you want to hide the Swagger UI from unauthorized users
)

urlpatterns = [
    
    #Lieu
    path('lieu/',views.LieuView.as_view(),name="list_lieux"),
    path('lieu/<int:lieu_id>/',views.details_Lieu, name='detail_Lieu'),
    #recupere tous les lieux d'un departement
    path('all_lieux_departement/<int:departement_id>', views.get_all_lieux_departement, name='get_all_lieux_departement'),
   
    #Parcours
    path('parcours/',views.ParcoursView.as_view(),name="list_Parcours"),
    path('parcours/<int:parcours_id>/',views.details_Parcours, name='detail_Parcours'),

    #Evenement
    path('evenement/',views.EvenementView.as_view(), name="list_evenements"),
    path('evenement/<int:evenement_id>/',views.detail_evenement_with_lieu, name='detail_evenement'),

    #Region
    path('region/',views.RegionView.as_view(),name="list_regions"),
    #recupere tous les lieux d'une region
    path('all_lieux_region/<int:region_id>', views.get_all_lieux_region, name='get_all_lieux_region'),

    #Departement
    path('departement/',views.DepartementView.as_view(), name="list_departements"),
    
    #Ville
    path('ville/',views.VilleView.as_view(), name="list_villes"),   
    
    #Horaire
    # path('horaire/',views.HoraireView.as_view(), ),
    
    #Tarif
    path('tarif/',views.TarifView.as_view(), name="list_tarifs"),
    
    #TypeLieu
    path('typelieu/',views.TypeLieuView.as_view(), name="list_typelieu"),

    #LnkLieuHoraire
    # path('lnklieuhoraire/',views.LnkLieuHoraireView.as_view(),),

    #FavorisParcours
    path('favorisparcours/',views.FavorisParcoursView.as_view(), name="list_favorisparcours"),

    #PreferenceLieu
    path('preferencelieu/',views.PreferenceLieuView.as_view(), name="list_preferencelieu"),

    #Oeuvre
    path('oeuvre/',views.OeuvreProximiteView.as_view(), name="list_oeuvres_proximite"),

    #recupere toutes les oeuvres à proximité dans un departement
    path('oeuvre/<int:departement_id>', views.get_all_oeuvres_proximites_departement, name='get_all_oeuvres_proximites_departement'),
    
    path('tojson/',views.tojson, name='tojson'),

    #partie token
    path('token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh', TokenRefreshView.as_view(), name='token_refresh_pair'),

    #creation utilisateur
    path('register/', views.RegisterView.as_view(), name='auth_register'),

    # Configuration drf-yasg pour la documentation Swagger
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    #modification informations utilisateur
    path('update-user/<int:user_id>',views.update_user, name='update-user'),

    #recuperer les parcours favoris d'un utilisateur
    path('favoris-parcours/<int:user_id>',views.get_favoris_parcours, name='get-favoris-parcours'),

    path('favoris-lieu/<int:user_id>',views.get_favoris_lieu, name='get-favoris-lieu'),


    #reste à faire 
    #recuperer les parcours d'un utilisateur

    #creation d'un parcours avec des etapes 

    #modification d'un parcours avec des etapes 

    #suppression d'un parcours avec ces etapes

]

SaeArtchipel/app_admin/urls.py
from django.urls import path
from .views import ParcoursProposeView, home, liste_regions, liste_departements, liste_villes, liste_typelieux, liste_lieux
from .views import RegionCreateView, RegionUpdateView, RegionDeleteView, DepartementCreateView, DepartementUpdateView, DepartementDeleteView, VilleCreateView, VilleUpdateView, VilleDeleteView, TypeLieuCreateView, TypeLieuUpdateView, TypeLieuDeleteView, LieuCreateView, LieuUpdateView, LieuDeleteView, HoraireView, LnkLieuHoraireView, ParcoursListView, ParcoursDetailView, DeleteViewParcours, ParcoursCreateView,edit_parcours, ListeEtape, add_etape_parcours, login_view, user_logout


app_name = 'app_admin'

urlpatterns = [
    path('',home, name='home' ),

    path('regions/', liste_regions, name='liste_regions'),
    path('region/ajouter/', RegionCreateView.as_view(), name='ajouter_region'),
    path('region/modifier/<int:pk>/', RegionUpdateView.as_view(), name='modifier_region'),
    path('region/supprimer/<int:pk>/', RegionDeleteView.as_view(), name='supprimer_region'),

    path('departements/', liste_departements, name='liste_departements'),
    path('departement/ajouter/', DepartementCreateView.as_view(), name='ajouter_departement'),
    path('departement/modifier/<int:pk>/', DepartementUpdateView.as_view(), name='modifier_departement'),
    path('departement/supprimer/<int:pk>/', DepartementDeleteView.as_view(), name='supprimer_departement'),

    path('villes/', liste_villes, name='liste_villes'),
    path('ville/ajouter/', VilleCreateView.as_view(), name='ajouter_ville'),
    path('ville/modifier/<int:pk>/', VilleUpdateView.as_view(), name='modifier_ville'),
    path('ville/supprimer/<int:pk>/', VilleDeleteView.as_view(), name='supprimer_ville'),

    path('typelieux/', liste_typelieux, name='liste_typelieux'),
    path('typelieu/ajouter/', TypeLieuCreateView.as_view(), name='ajouter_typelieu'),
    path('typelieu/modifier/<int:pk>/', TypeLieuUpdateView.as_view(), name='modifier_typelieu'),
    path('typelieu/supprimer/<int:pk>/', TypeLieuDeleteView.as_view(), name='supprimer_typelieu'),

    path('lieux/', liste_lieux, name='liste_lieux'),
    path('lieu/ajouter/', LieuCreateView.as_view(), name='ajouter_lieu'),
    path('lieu/modifier/<int:pk>/', LieuUpdateView.as_view(), name='modifier_lieu'),
    path('lieu/supprimer/<int:pk>/', LieuDeleteView.as_view(), name='supprimer_lieu'),

    path('horaire/<int:lieu_id>/', HoraireView.as_view(), name='horaire-view'),
    path('lnk-lieu-horaire/<int:lieu_id>/<int:horaire_id>/', LnkLieuHoraireView.as_view(), name='lnk-lieu-horaire-view'),

    path('parcours-liste/', ParcoursListView.as_view(), name='liste_parcours'),
    path('parcours-detail/<int:pk>/', ParcoursDetailView.as_view(), name='get_parcours'),
    path('supprimer-parcours/<int:pk>/', DeleteViewParcours.as_view(), name='delete_parcours'),
    path('creer-parcours/', ParcoursCreateView.as_view(), name='add_parcours'),
    path('proposer-parcours/', ParcoursProposeView.as_view(), name='pro_parcours'),
    path('parcours/edit/<int:parcours_id>/', edit_parcours, name='edit_parcours'),
    path('parcours_liste_etapes/<int:parcours_id>', ParcoursDetailView.as_view(), name='get_liste_etape' ),
    path('liste_all_lieux/<int:parcours_id>', ListeEtape.as_view(), name='liste_lieux_etapes'),
    path('ajouter_etape/', add_etape_parcours, name="ajouter_etape"),

    path('login/', login_view, name='login'),
    path('logout/', user_logout, name='logout'),


    # path('/regions/', liste_regions, name='liste_regions'),
    # path('/region/ajouter/', RegionCreateView.as_view(), name='ajouter_region'),
    # path('/region/modifier/<int:pk>/', RegionUpdateView.as_view(), name='modifier_region'),
    # path('/region/supprimer/<int:pk>/', RegionDeleteView.as_view(), name='supprimer_region'),

    # path('/regions/', liste_regions, name='liste_regions'),
    # path('/region/ajouter/', RegionCreateView.as_view(), name='ajouter_region'),
    # path('/region/modifier/<int:pk>/', RegionUpdateView.as_view(), name='modifier_region'),
    # path('/region/supprimer/<int:pk>/', RegionDeleteView.as_view(), name='supprimer_region'),

    # path('/regions/', liste_regions, name='liste_regions'),
    # path('/region/ajouter/', RegionCreateView.as_view(), name='ajouter_region'),
    # path('/region/modifier/<int:pk>/', RegionUpdateView.as_view(), name='modifier_region'),
    # path('/region/supprimer/<int:pk>/', RegionDeleteView.as_view(), name='supprimer_region'),

    # path('/regions/', liste_regions, name='liste_regions'),
    # path('/region/ajouter/', RegionCreateView.as_view(), name='ajouter_region'),
    # path('/region/modifier/<int:pk>/', RegionUpdateView.as_view(), name='modifier_region'),
    # path('/region/supprimer/<int:pk>/', RegionDeleteView.as_view(), name='supprimer_region'),
]

SaeArtchipel/app_admin/models.py
from django.db import models

# Create your models here.

import api.models

SaeArtchipel/app_admin/forms.py
import random
from django import forms
from api.models import Region, Departement, Ville, TypeLieu, Lieu, Tarif, Horaire, LnkLieuHoraire, Parcours, Etape  

class RegionForm(forms.ModelForm):
    class Meta:
        model = Region
        fields = ['nomRegion']
        error_messages = {
            'nomRegion': {
                'unique': "Ce nom de region est déjà utilisé.",
            }
        }

class DepartementForm(forms.ModelForm):
    class Meta:
        model = Departement
        fields = ['nomDepartement', 'numeroDepartement', 'idRegion']
        idRegion = forms.ModelChoiceField(queryset=Region.objects.all(), empty_label=None)

        error_messages = {
            'nomDepartement': {
                'unique': "Ce nom de departement est déjà utilisé.",
            }
        }

class VilleForm(forms.ModelForm):
    class Meta:
        model = Ville
        fields = ['nomVille', 'codePostal', 'idDepartement']
        idDepartement = forms.ModelChoiceField(queryset=Departement.objects.all(), empty_label=None)
        
        error_messages = {
            'nomVille': {
                'unique': "Ce nom de ville est déjà utilisé.",
            },
            'codePostal': {
                'max_length': "Le code postal doit avoir au maximum 5 chiffres.",
            }
        }

        def clean_codePostal(self):
            codePostal = self.cleaned_data.get('codePostal')

            # Vérifier si le code postal est négatif
            if codePostal and codePostal < 0:
                raise forms.ValidationError("Le code postal ne peut pas être négatif.")
            
            # Vérifier si le code postal a une longueur de 5 chiffres
            if codePostal is not None and len(str(codePostal)) != 5:
                raise forms.ValidationError("Le code postal doit avoir une longueur de 5 chiffres.")
            
            return codePostal

class TypeLieuForm(forms.ModelForm):
    class Meta:
        model = TypeLieu
        fields = ['nomTypeLieu']
        
        error_messages = {
            'nomTypeLieu': {
                'unique': "Ce nom de typelieu est déjà utilisé.",
            }
        }

class LieuForm(forms.ModelForm):
    class Meta:
        model = Lieu
        fields = ['nomLieu','descriptionLieu' , 'boolPompidouLieu', 'boolAccessibilite', 'boolParking', 'boolShopping', 'boolRepas',
                  'boolJaujeLieux', 'nombreMaxVisiteur', 'adresseLieu', 'latitudeLieu', 'longitudeLieu',
                  'telLieu', 'mailLieu', 'webLieu','observationLieu' ,'idVille', 'idTarif', 'idTypeLieu']
        
        idVille = forms.ModelChoiceField(queryset=Ville.objects.all(), empty_label="Sélectionner une ville")
        idTarif = forms.ModelChoiceField(queryset=Tarif.objects.all(), empty_label="Sélectionner un tarif")
        idtypeLieu = forms.ModelChoiceField(queryset=TypeLieu.objects.all(), empty_label="Sélectionner un type de lieu")
        error_messages = {
                'nomLieu': {
                    'unique': "Ce nom de lieu est déjà utilisé.",
                }
            }
    descriptionLieu = forms.CharField(widget=forms.Textarea, required=False)
    observationLieu = forms.CharField(widget=forms.Textarea, required=False)
    imageLieu = forms.ImageField(required=False)
    nombreMaxVisiteur = forms.IntegerField(min_value=1, required=True)
    adresseLieu = forms.CharField(required=False)
    latitudeLieu = forms.FloatField(required=False)
    longitudeLieu = forms.FloatField(required=False)
    telLieu = forms.IntegerField(required=False)
    mailLieu = forms.CharField(required=False)
    webLieu = forms.CharField(required=False)

class HoraireForm(forms.ModelForm):
    class Meta:
        model = Horaire
        fields = ['observationHoraire', 'horaireOuverture', 'horaireFermeture', 'intervalHoraire', 'lienReservationHoraire']


    observationHoraire = forms.CharField(widget=forms.Textarea, required=False)
    horaireOuverture = forms.TimeField(
        widget=forms.TimeInput(attrs={'type': 'time'}),
        label='Heure d\'ouverture',
        required=False
    )

    horaireFermeture = forms.TimeField(
        widget=forms.TimeInput(attrs={'type': 'time'}),
        label='Heure de fermeture',
        required=False
    )
    lienReservationHoraire = forms.CharField(required=False)

    def clean(self):
        cleaned_data = super().clean()
        ouverture = cleaned_data.get('horaireOuverture')
        fermeture = cleaned_data.get('horaireFermeture')

        if ouverture and fermeture and ouverture >= fermeture:
            raise forms.ValidationError("L'heure de fermeture doit être après l'heure d'ouverture.")

        return cleaned_data
    
class LnkLieuHoraireForm(forms.ModelForm):
    class Meta:
        model = LnkLieuHoraire
        fields = ['idLieu', 'idHoraire', 'dateDebut', 'dateFin']
    
    dateDebut = forms.DateField(required=True, widget=forms.SelectDateWidget(attrs={'class': 'datepicker'}))
    dateFin = forms.DateField(required=True, widget=forms.SelectDateWidget(attrs={'class': 'datepicker'}))

    def __init__(self, lieu_id=None, horaire_id=None, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if lieu_id:
            self.fields['idLieu'].initial = lieu_id
            self.fields['idLieu'].widget.attrs['readonly'] = True
            self.fields['idLieu'].disabled = True

        if horaire_id:
            self.fields['idHoraire'].initial = horaire_id
            self.fields['idHoraire'].widget.attrs['readonly'] = True
            self.fields['idHoraire'].disabled = True

    def clean(self):
        cleaned_data = super().clean()
        date_debut = cleaned_data.get('dateDebut')
        date_fin = cleaned_data.get('dateFin')

        if date_debut and date_fin and date_debut > date_fin:
            raise forms.ValidationError("La date de fin doit être après la date de début.")

        return cleaned_data
    
class ParcoursCreationForm(forms.ModelForm):
    DIFFICULTE_CHOICES = [
        ('facile', 'Facile'),
        ('modere', 'Moyen'),
        ('difficile', 'Difficile'),
    ]

    difficulteParcours = forms.ChoiceField(choices=DIFFICULTE_CHOICES, label='Difficulté du parcours')
    distanceParcours = forms.IntegerField(label="Distance du parcours (en km)")

    class Meta:
        model = Parcours
        fields = ['nomParcours', 'typeParcours', 'difficulteParcours', 'distanceParcours']

class ParcoursProposeForm(forms.ModelForm):
    departementDepart = forms.ModelChoiceField(queryset=Departement.objects.all(), empty_label="Sélectionner un departement de départ")
    disponibiliteJours = forms.IntegerField(min_value=1, required=True)

    class Meta:
        model = Parcours
        fields = ['nomParcours', 'typeParcours', 'difficulteParcours', 'distanceParcours']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial['nomParcours'] = self.generate_unique_parcours_name()
        self.initial['typeParcours'] = "TypeAleatoire"
        self.initial['difficulteParcours'] = "Aleatoire"
        self.initial['distanceParcours'] = random.randint(5, 50)

    def generate_unique_parcours_name(self):
        # Générer un nom aléatoire unique pour le parcours
        base_nom = 'Aleatoire'
        i = 1
        nom_unique = f"{base_nom}{i}"
        while Parcours.objects.filter(nomParcours=nom_unique).exists():
            i += 1
            nom_unique = f"{base_nom}{i}"
        return nom_unique

    def save(self, commit=True):
        instance = super(ParcoursProposeForm, self).save(commit=False)
        
        instance.nomParcours = self.cleaned_data['nomParcours']  # Utilisation du nom saisi dans le formulaire

        if commit:
            instance.save()

        return instance

class EtapeForm(forms.ModelForm):
    class Meta:
        model = Etape
        fields = ['idParcours', 'idLieu', 'numEtape']

SaeArtchipel/app_admin/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page d'accueil</title>

    <script src="https://kit.fontawesome.com/c055ab3298.js" crossorigin="anonymous"></script>

    {% block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% endblock %}
    {% block styles %}
    <link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}">
    {% endblock %}

    <script src="https://unpkg.com/htmx.org@1.9.7"></script>

    <style>

      .box{
        margin: .25rem ;
      }

    </style>
    
</head>
<body>

{% include 'navbar.html' %}

{% block content %}
{% endblock %}


{% block js %}
<script src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script  type="module" src="{% static 'node_modules/popper.js/dist/popper.min.js' %}"></script>
{% endblock %}

<script>
  document.body.addEventListener('htmx:configRequest', (event) => {
      event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
  })
  
  htmx.onLoad(function(content) {
      var sortables = content.querySelectorAll(".sortable");
      for (var i = 0; i < sortables.length; i++) {
          var sortable = sortables[i];
          var sortableInstance = new Sortable(sortable, {
              animation: 150,
              ghostClass: 'blue-background-class',

              // Make the `.htmx-indicator` unsortable
              filter: ".htmx-indicator",
              onMove: function (evt) {
                  return evt.related.className.indexOf('htmx-indicator') === -1;
              },

              // Disable sorting on the `end` event
              onEnd: function (evt) {
                  this.option("disabled", true);
              }
          });

          // Re-enable sorting on the `htmx:afterSwap` event
          sortable.addEventListener("htmx:afterSwap", function() {
              sortableInstance.option("disabled", false);
          });
      }
  })
</script>

</body>
</html>

SaeArtchipel/app_admin/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    

    <link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}">

</head>
<body>
    <div class="col-12 d-flex justify-content-center">
            <div class="row m-2">

         

    
                <h2>Login</h2>
                <p>Reserver pour les administrateurs d'Artchipel</p>
            
                <!-- {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %} -->
            
                <form method="post" action="{% url 'app_admin:login' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Login</button>
                </form>
            </div>
        

    </div>
    
</body>
</html>

SaeArtchipel/app_admin/templates/navbar.html
    <header>
      <nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'app_admin:home' %}"><i class="fa-solid fa-house"></i></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                

              <li class="nav-item">
                <a class="nav-link" href="{% url 'app_admin:liste_villes' %}">Villes</a>
                </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app_admin:liste_lieux' %}">Lieux</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app_admin:liste_parcours' %}">Parcours</a>
              </li>
            </ul>
            <!-- <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-primary" type="submit">Search</button>
            </form> -->

            <div class="text-end">
              <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app_admin:logout' %}">Logout</a>
              </li>
              {% endif %}
            </ul>
            </div>


          </div>


        </div>
      </nav>
    </header>